### PR TITLE
update cowboy to 2.6.1

### PR DESCRIPTION
**Pull request by getong**
cowlib is included by cowboy
I think rebar.lock is need by erlang project, add it.

### CODE REVIEW

**Comment by gotthardp** [comment]
Hello. On the contrary, rebar.lock is auto-generated and shouldn't be included in the repository.

**Comment by getong** [comment]
Yes, the lock file us auto generated, but it helps to check the deps hash.

**Comment by getong** [comment]
Only updating the version, I think this pr can be merged.

**Comment by gotthardp** [comment]
The trouble is that I also use Gun and its latest release still uses the cowlib 2.6.0. I'd prefer to use Cowboy and Gun versions that depend on the same Cowlib version, so I'd prefer to stay with Cowboy 2.5.0 for now. Unless we really have to migrate due to a bug fix or some feature that you need, which is available only on Cowboy 2.6.0.

**Pull request closed without merging**
