### PR TITLE
Force wget to IPv4 only. We don't support IPv6 yet.

### PR DESCRIPTION
**Pull request by altishchenko**
This will quiet the 'connection refused' error.

### CODE REVIEW

**Comment by gotthardp** [comment]
This looks OK, but IPv6 seems to be just one config option (adding `inet6` to the listen options). I wonder if it wouldn't be better to enable IPv6 by default instead. What do you think?

**Comment by altishchenko** [comment]
Well, I think this will stop questions on the line - "Why are we getting
'Connection Refused' while exporting or importing our settings?". 'Cause
the way it works is - wget tries IPv6 first, gets knocked out and prints
the error message, then it tries IPv4 and succeeds and saves the file. I
just remembered an old issue with 'Why am I seeing Refused on export and
import' and you answered that this is just wget and you don't know what
makes it do so. Now I know :)

**Comment by altishchenko** [comment]
And another 'No' - how many base stations support v6? It is a good mark for
the future and should be enabled by default, possibly via config or
something, but it is not happening yet, no matter what RIPE tries to tell
people - them vendors are not there to support the case at the full scale.

Sorry,
Alexander Tishchenko

**Comment by gotthardp** [comment]
And I am happy that you discovered this. Many people are asking the "why the error" question.

**Pull request merged**
